on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  Get-NBA-PBP:
    name: Get Latest NBA PBP Data 
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3  
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     WIP:   
      # - name: Cache CRAN packages
      #   uses: actions/cache@v3 
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
      #     restore-keys: ${{ runner.os }}-r-
          
      # - name: Install CRAN packages
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with: 
      #     packages: jsonlite, dplyr
          
      # - name: Run R update script
      #   run: Rscript get_mvp_odds.R
      #   shell: bash

      # - name: Commit changes in data folder
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add data/mvp_odds*.csv
      #     git diff --cached --quiet || git commit -m "Auto-update: mvp odds"
      #   shell: bash

      # - name: Push changes
      #   run: git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
